spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/melnitsa_crm
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate # Не создает таблицы автоматически!
    show-sql: true